# term xterm-256color

font_family Iosevka Term
font_size 11.0
text_composition_strategy legacy

map ctrl+plus change_font_size all +2.0
map ctrl+equal change_font_size all +2.0
map ctrl+minus change_font_size all -2.0

enable_audio_bell no

# See: map cmd+shift+k combine : clear_terminal scroll active : clear_terminal scrollback active
map ctrl+l combine : clear_terminal scroll active : clear_terminal scrollback active

kitty_mod ctrl+shift

# Tmux-like layout
# See: 
# - https://sw.kovidgoyal.net/kitty/conf/#window-management
# - https://sw.kovidgoyal.net/kitty/actions/#action-new_os_window_with_cwd
map kitty_mod+enter new_os_window_with_cwd
map kitty_mod+, set_window_title " "
map kitty_mod+n new_window_with_cwd
map kitty_mod+q close_window
map kitty_mod+h next_window
map kitty_mod+l next_window
map kitty_mod+] next_tab
map kitty_mod+[ previous_tab
map kitty_mod+t new_tab_with_cwd

# Rely on OS color scheme instead of hardcoding a theme.
# See: https://sw.kovidgoyal.net/kitty/kittens/themes/#change-color-themes-automatically-when-the-os-switches-between-light-and-dark
#include themes/base16-default-dark-256.conf
