#!/usr/bin/env sh
#require: os=linux distro=arch|archarm
#description: dotfiles and packages for Arch Linux

param system 'validate:desktop|framework13|macbookProIntel|qemu|other' 'description:Target system type' required

arch_pacman_install() {
  pacmanfile 'packages.list'

  rustup default stable
  aurpkg 'paru'
  paru -S perl-perl-languageserver --noconfirm --needed

  gsettings set org.blueman.general notification-daemon true
}

require 'common'

# Deps
step arch_pacman_install 'flag:pkgs'

HYPRLAND_PLATFORM_CFG="$XDG_CONFIG_HOME/hypr/hyprland.d/targets/platform-autogenerated.conf"
expand_template \
  'templates/hyprland-vars.conf' \
  "$HYPRLAND_PLATFORM_CFG" \
  "target=$(get_param 'system')"

# Wallpapers
link_home 'Pictures/wallpapers' 'wallpapers'

# Configs
link_xdg_config config

# Extra binaries
link_home '.local/bin' bin
