#!/usr/bin/env sh
#require: os=linux distro=arch|archarm
#description: dotfiles and packages for Arch Linux
#variants: desktop|framework13|macbookProIntel|qemu|other

arch_pacman_install() {
  pacmanfile 'packages.list'

  rustup default stable
  aurpkg 'paru'
  aurfile 'aur.list'
  gsettings set org.blueman.general notification-daemon true
}

HYPRLAND_PLATFORM_CFG="$XDG_CONFIG_HOME/hypr/hyprland.d/targets/platform-autogenerated.conf"
arch_hyprland_configs() {
  expand_template \
    'templates/hyprland-vars.conf' \
    "$HYPRLAND_PLATFORM_CFG" \
    "target=$(current_variant)"
}

require 'common'

# Deps
step arch_pacman_install 'flag:pkgs'

# Wallpapers
link_home 'Pictures/wallpapers' 'wallpapers'

# Configs
link_xdg_config config
link_home dotfiles

# Hyprland configs
step arch_hyprland_configs

# Extra binaries
link_home '.local/bin' bin
